name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.03
        extra_nix_config: |
                            substituters = https://cache.nixos.org https://cache.nixos.org/ https://hydra.iohk.io https://cachix.cachix.org https://iohk.cachix.org https://ghcide-nix.cachix.org https://mostlyabsurd.cachix.org https://absurd-paste-client.cachix.org
                            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cachix.cachix.org:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= all-hies.cachix.org-1:JjrzAOEUsD9ZMt8fdFbzo3jNAyEWlPAwdVuHw4RD43k= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= ghcide-nix.cachix.org-1:ibAY5FD+XWLzbLr8fxK6n8fL9zZe7jS+gYeyxyWYK5c= mostlyabsurd.cachix.org-1:WoFsXSqFZNZj9+1TcbfiEdAmP5T20oQoU7jIi4RlcVU=
    - uses: cachix/cachix-action@v8
      with:
        name: absurd-paste-client
        # If you chose signing key for write access
        #signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: iohk
    - run: nix-build
    - run: nix-shell --run "echo OK"
